[project]
name = "sychronous-vs-asychronous"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent>=0.1.3",
    "load-dotenv>=0.1.0",
    "openai-agents>=0.2.3",
]
